services:
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"

  resume-data:
    build: ./services/resume-data-dotnet/ResumeDataService
    ports:
      - "5000:80"

  project-showcase:
    build: ./services/project-showcase-node
    ports:
      - "4000:3000"

  analytics:
    build: ./services/analytics-python
    ports:
      - "8000:8000"

  contact-form:
    build: ./services/contact-form-node
    ports:
      - "4001:3000"

  social-links:
    build: ./services/social-links
    ports:
      - "4002:3000"

  auth-service:
    build: ./services/auth-service-node
    ports:
      - "4003:3000"

